import SalesPolicy from './SalesPolicy';
import React, { useState } from 'react';
import axios from '../../api/axiosInstance';
export default function AcquisitionReport() {
  const [from,setFrom]=useState(''),[to,setTo]=useState('');
  const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function load(){setBusy(true);setError('');try{const r=await axios.get('/reports/acquisition',{params:{from:from?new Date(from).toISOString():undefined,to:to?new Date(to).toISOString():undefined}});setData(r.data.data);}catch(e){setError(e.response?.data?.message||e.message);}finally{setBusy(false);}}
  async function download(){try{const r=await axios.get('/reports/acquisition',{params:{export:'true',from:from?new Date(from).toISOString():undefined,to:to?new Date(to).toISOString():undefined}});const u=URL.createObjectURL(new Blob([JSON.stringify(r.data.data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='acquisition-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){setError(e.response?.data?.message||e.message);}}
  return <section className="border rounded p-5 my-5 space-y-4"><h2 className="text-xl font-semibold">Acquisition command center</h2><SalesPolicy/><div className="flex flex-wrap gap-3"><label>Period from<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label></div><button className="border rounded px-4 py-2" disabled={busy} onClick={load}>{busy?'Loading…':'Refresh acquisition report'}</button><button className="border rounded px-4 py-2" onClick={download}>Download period report</button>{error&&<p role="alert">{error}</p>}{data&&<>
    <p>Generated {new Date(data.generatedAt).toLocaleString()}. Funnel and lead breakdowns use the selected period. Campaign economics show cumulative lifetime results. Financial values remain unavailable until evidenced.</p>
    <div className="overflow-auto"><table className="w-full text-left"><thead><tr>{['Campaign','Leads','Qualified','Quotes','Orders','Actual spend','CPL','CPQL'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{data.campaigns.map(c=><tr key={c.campaign.id}>{[c.campaign.utmCampaign,c.observed.overall.leads,c.observed.overall.qualifiedLeads,c.observed.overall.quotes,c.observed.overall.orders,c.financial.actualSpend?`${c.financial.currency} ${c.financial.actualSpend.amount}`:'Unavailable',c.financial.cpl??'Unavailable',c.financial.cpql??'Unavailable'].map((v,i)=><td className="p-2" key={i}>{v}</td>)}</tr>)}</tbody></table></div>
    {data.campaigns.map(c=><div key={c.campaign.id}><h3>{c.campaign.utmCampaign} — actual financial outcomes by currency</h3>{Object.entries(c.financial.byCurrency).map(([currency,v])=><p key={currency}>{currency}: revenue {v.revenue??'Unavailable'}; gross profit {v.grossProfit??'Unavailable'} ({v.observedOrders} evidenced orders)</p>)}</div>)}
    <p>Still new: {data.responseTime.stillNewLeads}; untouched hot leads: {data.responseTime.untouchedHotLeads}; overdue follow-ups: {data.responseTime.overdueFollowups}; average first response: {data.responseTime.responseTime.averageMinutes??'Unavailable'} minutes.</p>
    <details><summary>Funnel, segments and lost-reason breakdown</summary><h3>Funnel events</h3><ul>{data.funnel.map((row,i)=><li key={i}>{row._id.vertical || 'Unspecified product'} ? {row._id.event.replaceAll('_',' ')}: {row.count}</li>)}</ul><h3>Lead outcomes</h3><ul>{data.leadBreakdown.map((row,i)=><li key={i}>{Object.values(row._id).filter(Boolean).join(' ? ')}: {row.count}</li>)}</ul><h3>Journey segments</h3><ul>{Object.entries(data.audiences).map(([label,count])=><li key={label}>{label.replace(/([A-Z])/g,' $1')}: {count}</li>)}</ul><p>{data.audienceUse}</p></details>
    <ul>{data.diagnostics.map(([stage,reason])=><li key={stage}>{stage}: {reason}</li>)}</ul>
  </>}</section>;
}
