import CustomerOrders from './CustomerOrders';
import React, { useState } from 'react';
import axios from '../../api/axiosInstance';
import toast from 'react-hot-toast';

export default function LeadCommercialPanel({lead,user,onSaved}) {
  const [form,setForm]=useState({crmStatus:'CONTACT_ATTEMPTED',note:'',lostReason:'',lostReasonNotes:'',currency:'',revenue:'',grossProfit:'',orderReference:'',evidenceReference:'',status:'REVIEW_REQUIRED',reference:'',notes:'',customerAccountId:'',customerAccountType:'USER'});
  const [quotes,setQuotes]=useState([]),[selected,setSelected]=useState(''),[terms,setTerms]=useState({});
  const management=['ADMIN','FOUNDER','CO_FOUNDER','SUPER_ADMIN'].includes(user?.role)||['ADMIN','MANAGEMENT'].includes(user?.department);
  const ops=user?.department==='OPERATIONS',finance=management||['FINANCE','ACCOUNTS'].includes(user?.department);
  const input=(key,label)=> <label className="block" key={key}>{label}<input className="block border rounded p-2 bg-transparent w-full" value={form[key]} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))}/></label>;
  async function save(path,payload) {try{await axios.patch(`/leads/${lead._id}/${path}`,payload);toast.success('Saved');await onSaved?.();}catch(e){toast.error(e.response?.data?.message||e.message);}}
  async function loadQuotes(){try{const r=await axios.get(`/quotations/lead/${lead._id}/commercial`);setQuotes(r.data.data.quotations);}catch(e){toast.error(e.response?.data?.message||e.message);}}
  async function saveTerms(e){e.preventDefault();try{const payload={...terms};for(const key of ['quantity','unitPrice','freight','tax'])payload[key]=terms[key]===''?null:Number(terms[key]);await axios.patch(`/quotations/${selected}/commercial-terms`,payload);toast.success('Operations terms recorded; Management approval required.');await loadQuotes();}catch(e){toast.error(e.response?.data?.message||e.message);}}
  async function pdf(id){try{const r=await axios.get(`/quotations/${id}/pdf`,{responseType:'blob'});const url=URL.createObjectURL(r.data),a=document.createElement('a');a.href=url;a.download=`quotation-${id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{toast.error('Quotation PDF is unavailable. Confirm current terms and approval.');}}
  return <section className="m-4 p-4 border rounded space-y-4">
    <CustomerOrders user={user} leadId={lead?._id}/><h2 className="font-semibold">Commercial lifecycle and outcomes</h2><p>CRM status: {lead.crmStatus || 'NEW'}</p>
    <details><summary>Record CRM progress</summary><form className="space-y-3" onSubmit={e=>{e.preventDefault();save('status',{crmStatus:form.crmStatus,note:form.note,lostReason:form.lostReason,lostReasonNotes:form.lostReasonNotes});}}>
      <select value={form.crmStatus} onChange={e=>setForm(v=>({...v,crmStatus:e.target.value}))}>{['CONTACT_ATTEMPTED','CONTACTED','QUALIFIED','QUOTATION_SENT','NEGOTIATION','WON','LOST'].map(s=><option key={s}>{s}</option>)}</select>{input('note','Factual progress note')}
      {form.crmStatus==='LOST' && <><select required value={form.lostReason} onChange={e=>setForm(v=>({...v,lostReason:e.target.value}))}><option value="">Select lost reason</option>{['PRICE','FREIGHT','COMPETITOR','UNSUPPORTED_DESTINATION','QUANTITY_TOO_LOW','PRODUCT_UNAVAILABLE','NO_RESPONSE','INVALID_CONTACT','TIMING','PAYMENT_TERMS','TRUST_CONCERN','OTHER'].map(s=><option key={s}>{s}</option>)}</select>{input('lostReasonNotes','Lost reason details')}</>}<button className="border p-2">Save progress</button></form></details>
    {ops && <details><summary>Operations serviceability review</summary><form onSubmit={e=>{e.preventDefault();save('serviceability',{status:form.status,reference:form.reference,notes:form.notes});}}><select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value}))}>{['REVIEW_REQUIRED','ELIGIBLE','NOT_ELIGIBLE'].map(s=><option key={s}>{s}</option>)}</select>{input('reference','Operations evidence')}{input('notes','Facts and restrictions')}<button className="border p-2">Record review</button></form></details>}
    {finance && <details><summary>Actual financial outcome</summary><form onSubmit={e=>{e.preventDefault();save('commercial-outcome',{currency:form.currency,revenue:form.revenue===''?null:Number(form.revenue),grossProfit:form.grossProfit===''?null:Number(form.grossProfit),orderReference:form.orderReference,evidenceReference:form.evidenceReference});}}>{['currency','revenue','grossProfit','orderReference','evidenceReference'].map(key=>input(key,key))}<p>Leave unknown amounts blank. Requires a won order.</p><button className="border p-2">Record actual outcome</button></form></details>}
    {management && <details><summary>Verify customer account linkage</summary><form onSubmit={e=>{e.preventDefault();save('customer-account',{customerAccountId:form.customerAccountId,customerAccountType:form.customerAccountType,reference:form.reference});}}>{input('customerAccountId','Verified customer account ID')}<select value={form.customerAccountType} onChange={e=>setForm(v=>({...v,customerAccountType:e.target.value}))}><option>USER</option><option>DISTRIBUTOR</option></select>{input('reference','Identity verification evidence')}<button className="border p-2">Link verified account</button></form></details>}
    <details><summary onClick={loadQuotes}>Quotation terms and PDF</summary>{quotes.map(q=><div key={q._id} className="border p-3 my-2"><p>{q._id} · {q.status}</p>{q.commercialTerms && <p>{q.commercialTerms.currency} {q.commercialTerms.quantity*q.commercialTerms.unitPrice+q.commercialTerms.freight+q.commercialTerms.tax}</p>}<button type="button" onClick={()=>pdf(q._id)} className="underline mr-4">Download approved PDF</button>{ops&&<button type="button" onClick={()=>{setSelected(q._id);setTerms(q.commercialTerms||{});}}>Edit Operations terms</button>}<button type="button" onClick={async()=>{try{await axios.patch(`/quotations/${q._id}/sent-to-customer`,{note:form.note});await loadQuotes();toast.success('Quotation marked shared.');}catch(e){toast.error(e.response?.data?.message||e.message);}}}>Mark actually shared</button></div>)}
      {ops&&selected&&<form onSubmit={saveTerms} className="grid gap-3 md:grid-cols-2">{['source','product','destination','unit','currency','quantity','unitPrice','freight','tax','validUntil','deliveryTerms','paymentTerms','reference'].map(key=><label key={key}>{key}<input required className="block border p-2 bg-transparent w-full" type={key==='validUntil'?'date':'text'} value={terms[key]??''} onChange={e=>setTerms(v=>({...v,[key]:e.target.value}))}/></label>)}<button className="border p-2">Confirm Operations terms</button></form>}
    </details>
  </section>;
}
