const LEAD_STAGES = {
  NEW_LEAD: 'NEW_LEAD',
  ASSIGNED: 'ASSIGNED',
  CONTACTED: 'CONTACTED',
  LEAD_QUALIFICATION: 'LEAD_QUALIFICATION',
  FOLLOW_UP: 'FOLLOW_UP',
  REQUIREMENT_CAPTURED: 'REQUIREMENT_CAPTURED',
  QUOTATION_REQUIRED: 'QUOTATION_REQUIRED',
  QUOTATION_REQUESTED: 'QUOTATION_REQUESTED',
  QUOTATION_SHARED: 'QUOTATION_SHARED',
  DISPATCH_PLANNED: 'DISPATCH_PLANNED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  DOCUMENT_PENDING: 'DOCUMENT_PENDING',
  CLOSED_WON: 'CLOSED_WON',
  CLOSED_LOST: 'CLOSED_LOST',
  
  // New pipeline stages
  REQUIREMENT_RECEIVED: 'REQUIREMENT_RECEIVED',
  QUOTATION_SENT: 'QUOTATION_SENT',
  SAMPLE_SENT: 'SAMPLE_SENT',
  PRICE_DISCUSSION: 'PRICE_DISCUSSION',
  PAYMENT_DISCUSSION: 'PAYMENT_DISCUSSION',
  PO_RECEIVED: 'PO_RECEIVED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  DEAL_WON: 'DEAL_WON',
  DEAL_LOST: 'DEAL_LOST'
};

const allowedStageTransitions = {
  [LEAD_STAGES.NEW_LEAD]: [LEAD_STAGES.ASSIGNED, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.CONTACTED, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.ASSIGNED]: [LEAD_STAGES.CONTACTED, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.CONTACTED]: [LEAD_STAGES.QUOTATION_REQUIRED, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.FOLLOW_UP, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.LEAD_QUALIFICATION]: [LEAD_STAGES.FOLLOW_UP, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.FOLLOW_UP]: [LEAD_STAGES.REQUIREMENT_CAPTURED, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.REQUIREMENT_RECEIVED, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.REQUIREMENT_CAPTURED]: [LEAD_STAGES.QUOTATION_REQUIRED, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.QUOTATION_REQUIRED]: [LEAD_STAGES.QUOTATION_REQUESTED, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.QUOTATION_REQUESTED]: [LEAD_STAGES.QUOTATION_SHARED, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.QUOTATION_SHARED]: [LEAD_STAGES.DISPATCH_PLANNED, LEAD_STAGES.CLOSED_WON, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.DISPATCH_PLANNED]: [LEAD_STAGES.PAYMENT_PENDING, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.PAYMENT_PENDING]: [LEAD_STAGES.DOCUMENT_PENDING, LEAD_STAGES.CLOSED_WON, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.DOCUMENT_PENDING]: [LEAD_STAGES.CLOSED_WON, LEAD_STAGES.CLOSED_LOST, LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.CLOSED_WON]: [],
  [LEAD_STAGES.CLOSED_LOST]: [],

  // New pipeline transitions
  [LEAD_STAGES.REQUIREMENT_RECEIVED]: [LEAD_STAGES.QUOTATION_SENT, LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.QUOTATION_SENT]: [LEAD_STAGES.NEGOTIATION, LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.NEGOTIATION]: [LEAD_STAGES.SAMPLE_SENT, LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.SAMPLE_SENT]: [LEAD_STAGES.PRICE_DISCUSSION, LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.PRICE_DISCUSSION]: [LEAD_STAGES.PAYMENT_DISCUSSION, LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.PAYMENT_DISCUSSION]: [LEAD_STAGES.PO_RECEIVED, LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.PO_RECEIVED]: [LEAD_STAGES.ORDER_CONFIRMED, LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.ORDER_CONFIRMED]: [LEAD_STAGES.DEAL_WON, LEAD_STAGES.DEAL_LOST],
  [LEAD_STAGES.DEAL_WON]: [],
  [LEAD_STAGES.DEAL_LOST]: []

function generateLeadCode() {
  const timestamp = Date.now();
  const random = Math.floor(Math.random() * 10000);
  return `LD-${timestamp}-${random}`;
}

function canAccessLead(user, lead) {
  if (!user) return false;
  if (user.role === 'ADMIN' || user.role === 'MANAGER' || user.role === 'HR') return true;
  if (lead.assignedTo && lead.assignedTo.toString() === user._id.toString()) return true;
  return false;
}

function getLeadDisplay(lead) {
  const leadObj = lead.toObject ? lead.toObject() : lead;
  return {
    ...leadObj,
    phone: leadObj.phoneMasked,
    email: leadObj.emailMasked
  };
}

function stageNeedsQuotation(stage) {
  return stage === LEAD_STAGES.QUOTATION_REQUIRED || stage === LEAD_STAGES.QUOTATION_REQUESTED;
}

module.exports = {
  LEAD_STAGES,
  allowedStageTransitions,
  generateLeadCode,
  canAccessLead,
  getLeadDisplay,
  stageNeedsQuotation
};