import React,{useState} from 'react';
import axios from '../api/axiosInstance';
import {getAnalyticsConsent,pushDprEvent,DPR_EVENTS} from '../utils/analytics';
export default function RepeatRequirement({lead}){
  const [form,setForm]=useState({submissionId:crypto.randomUUID(),phone:'',quantity:'',destination:'',timeline:'',contact:false,grade:'',packaging:'',tradeType:'DOMESTIC'}),[message,setMessage]=useState('');
  async function submit(e){e.preventDefault();try{const consent=getAnalyticsConsent();const r=await axios.post(`/customer-portal/leads/${lead._id}/reorder`,{...form,quantityMode:'CUSTOM',consent:{contactAllowed:form.contact,marketingAllowed:false,analyticsAllowed:consent.analytics,advertisingAllowed:consent.advertising,privacyVersion:'privacy-policy-2026-09'}},{headers:{'X-Portal-Context':localStorage.getItem('distributor_token')?'customer':'admin'}});pushDprEvent(DPR_EVENTS.LEAD_CREATED,{product_category:lead.productCategory},{eventId:r.data.data.leadCreatedEventId});setMessage(`New requirement saved: ${r.data.data.leadCode}. Sales will review current terms.`);}catch(e){setMessage(e.response?.data?.message||e.message);}}
  if(lead.productCategory==='ITO_ADS')return null;
  return <details><summary>Repeat this product requirement</summary><form onSubmit={submit} className="grid gap-3 md:grid-cols-2">{['phone','quantity','destination','timeline',...(lead.productCategory==='STONE'?[]:['grade','packaging'])].map(k=><label key={k}>{k}{k==='quantity'&&lead.productCategory==='STONE'?' (MT)':''}<input required value={form[k]} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))} className="block border p-2"/></label>)}{lead.productCategory!=='STONE'&&<select value={form.tradeType} onChange={e=>setForm(v=>({...v,tradeType:e.target.value}))}><option>DOMESTIC</option><option>EXPORT</option></select>}<label><input type="checkbox" required checked={form.contact} onChange={e=>setForm(v=>({...v,contact:e.target.checked}))}/> I consent to contact about this new enquiry under the <a href="/privacy-policy">Privacy Policy</a>.</label><button className="border p-2">Submit new requirement</button><p role="status">{message}</p></form></details>;
}
