import RepeatRequirement from '../../components/RepeatRequirement';
import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import axios from '../../api/axiosInstance';

export default function CustomerPortal(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[po,setPo]=useState({}),[accepted,setAccepted]=useState({});
  const config={headers:{'X-Portal-Context':localStorage.getItem('distributor_token')?'customer':'admin'}};
  async function load(){try{const r=await axios.get('/customer-portal',config);setData(r.data.data);setError('');}catch(e){setError(e.response?.data?.message||'Sign in with your customer account to continue.');}}
  async function accept(id){try{await axios.post(`/customer-portal/quotations/${id}/accept`,{acceptTerms:accepted[id]===true,purchaseOrderReference:po[id]||''},config);await load();}catch(e){setError(e.response?.data?.message||e.message);}}
  async function pdf(id){try{const r=await axios.get(`/customer-portal/quotations/${id}/pdf`,{...config,responseType:'blob'});const u=URL.createObjectURL(r.data),a=document.createElement('a');a.href=u;a.download=`quotation-${id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch{setError('Shared PDF unavailable. Contact your sales representative.');}}
  return <main className="max-w-5xl mx-auto px-6 py-32 space-y-6"><h1 className="text-3xl">Your commercial account</h1><p>View quotations, orders and documents linked to your verified account.</p><Link className="underline" to="/login">Sign in</Link><button className="border p-3" onClick={load}>Load my account</button>{error&&<p role="alert">{error}</p>}
    {data&&<><h2 className="text-xl">Quotations</h2>{!data.quotations.length&&<p>No shared quotations. Ask Sales to verify your account linkage.</p>}{data.quotations.map(q=><article key={q._id} className="border rounded p-4 space-y-2"><h3>Quotation {q._id}</h3><p>{q.commercialTerms?.product} · {q.commercialTerms?.quantity} {q.commercialTerms?.unit} · {q.commercialTerms?.destination}</p>{q.commercialTerms&&<><p>{q.commercialTerms.currency} {q.commercialTerms.quantity*q.commercialTerms.unitPrice+q.commercialTerms.freight+q.commercialTerms.tax}</p><p>Delivery: {q.commercialTerms.deliveryTerms}. Payment: {q.commercialTerms.paymentTerms}. Valid until: {new Date(q.commercialTerms.validUntil).toLocaleDateString()}.</p></>}<button className="underline" onClick={()=>pdf(q._id)}>Download quotation PDF</button><label className="block">PO reference (optional)<input className="border p-2" value={po[q._id]||''} onChange={e=>setPo(v=>({...v,[q._id]:e.target.value}))}/></label><label className="block"><input type="checkbox" checked={accepted[q._id]===true} onChange={e=>setAccepted(v=>({...v,[q._id]:e.target.checked}))}/> I accept this quotation's product, quantity, price, delivery and payment terms.</label><button disabled={!accepted[q._id]} className="border p-2" onClick={()=>accept(q._id)}>Accept for order review</button></article>)}
    <h2 className="text-xl">Orders and documents</h2>{data.orders.map(o=><article className="border rounded p-4" key={o._id}><p>Order {o._id}: {o.status.replaceAll('_',' ')}</p><p>{o.currency} {o.amount} · Payment: {o.paymentStatus.replaceAll('_',' ')}</p>{o.documents.map(d=><a key={d._id} className="block underline" href={d.url} target="_blank" rel="noopener noreferrer">{d.title}</a>)}</article>)}
    <h2 className="text-xl">Request a repeat supply</h2><p>A new request requires current availability and commercial review.</p>{data.leads.map(l=><div key={l._id} className="border p-3"><p>{l.leadCode}: {l.product} · {l.quantity} · {l.destination}</p><RepeatRequirement lead={l}/><Link className="underline" to={l.productCategory==='RICE'?'/prakriti/rice#commercial-requirement':l.productCategory==='TEA'?'/prakriti#commercial-requirement':l.productCategory==='ITO_ADS'?'/ito-ads#commercial-requirement':'/stone'}>Start a new requirement</Link></div>)}</>}
  </main>;
}
